/**
 * opencode-memory — Archive Index Manager (v0.3.4 Phase 0)
 *
 * Manages the ARCHIVE.md manifest file. ARCHIVE.md is a sibling to MEMORY.md,
 * containing index entries for archived memories only.
 *
 * Design (D scheme — see docs/superpowers/specs/v0.3.4/04-archive-index.md):
 * - Lazy-create: ARCHIVE.md is created on first archive, deleted when empty
 * - AUTO-GENERATED header preserved on all writes
 * - Format matches MEMORY.md (buildIndexLine): `- [Title](file.md) — hook`
 * - File body content NEVER stored in manifest — only index pointers
 *
 * Atomicity contract (R2): manifest writes happen BEFORE frontmatter writes
 * in RepairService.archive(). This module provides helpers for the manifest
 * side of that contract.
 */

import { readFile, writeFile, unlink, mkdir } from "node:fs/promises"
import { existsSync } from "node:fs"
import { join, dirname } from "node:path"
import {
  type ArchiveEntry,
  buildArchiveLine,
  parseArchiveLine,
  MANIFEST_AUTO_GENERATED_HEADER,
  isAutoGeneratedHeaderLine,
} from "../lifecycle/archive-types.js"

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

/** Resolve ARCHIVE.md path for a given memory dir. */
export function getArchiveManifestPath(memoryDir: string): string {
  return join(memoryDir, "ARCHIVE.md")
}

/** Resolve MEMORY.md path for a given memory dir. */
export function getActiveManifestPath(memoryDir: string): string {
  return join(memoryDir, "MEMORY.md")
}

// ---------------------------------------------------------------------------
// Read — parse ARCHIVE.md into entries
// ---------------------------------------------------------------------------

/**
 * Read all entries from ARCHIVE.md.
 *
 * Returns empty array if ARCHIVE.md does not exist (fresh install or no
 * archived files — this is correct per lazy-create principle).
 *
 * Skips the AUTO-GENERATED header line and any non-manifest lines (blank
 * lines, comments, etc.).
 */
export async function readArchive(memoryDir: string): Promise<ArchiveEntry[]> {
  const archivePath = getArchiveManifestPath(memoryDir)
  if (!existsSync(archivePath)) return []

  const content = await readFile(archivePath, "utf-8")
  const entries: ArchiveEntry[] = []

  for (const line of content.split(/\r?\n/)) {
    if (line.trim() === "") continue
    if (isAutoGeneratedHeaderLine(line)) continue
    const parsed = parseArchiveLine(line)
    if (!parsed) continue // skip non-manifest lines (comments, etc.)
    entries.push({
      filename: parsed.filename,
      title: parsed.title,
      description: parsed.description,
      archivedAt: 0, // manifest doesn't store epoch ms; caller must enrich from file frontmatter if needed
    })
  }

  return entries
}

// ---------------------------------------------------------------------------
// Write — serialize entries to ARCHIVE.md (full regeneration)
// ---------------------------------------------------------------------------

/**
 * Write ARCHIVE.md with the given entries (full regeneration, not append).
 *
 * Always prepends the AUTO-GENERATED header. If entries is empty, the file
 * is DELETED instead (lazy-create principle: no archived files = no ARCHIVE.md).
 *
 * Sorting: entries are sorted by filename (alphabetical) for idempotent
 * rebuild (AC-4 — hash must be stable across runs).
 */
export async function writeArchive(
  memoryDir: string,
  entries: ArchiveEntry[],
): Promise<void> {
  const archivePath = getArchiveManifestPath(memoryDir)

  if (entries.length === 0) {
    // Lazy-delete: empty archive → no ARCHIVE.md file
    if (existsSync(archivePath)) {
      await unlink(archivePath).catch(() => {})
    }
    return
  }

  // Sort by filename for idempotent output (AC-4)
  const sorted = [...entries].sort((a, b) =>
    a.filename < b.filename ? -1 : a.filename > b.filename ? 1 : 0,
  )

  const lines = [
    MANIFEST_AUTO_GENERATED_HEADER,
    "", // blank line after header
    ...sorted.map(buildArchiveLine),
  ]
  const content = lines.join("\r\n") + "\r\n"

  // Ensure parent dir exists (memory dir should always exist, but defensive)
  await mkdir(dirname(archivePath), { recursive: true }).catch(() => {})
  await writeFile(archivePath, content, "utf-8")
}

// ---------------------------------------------------------------------------
// Add — append a single entry to ARCHIVE.md (incremental, used by archive())
// ---------------------------------------------------------------------------

/**
 * Add a single entry to ARCHIVE.md.
 *
 * Used by RepairService.archive() for incremental manifest sync (avoids full
 * rewrite on every archive op). Lazy-creates ARCHIVE.md if not exists.
 *
 * Idempotent: if an entry with the same filename already exists, it is
 * replaced (not duplicated).
 */
export async function addEntry(
  memoryDir: string,
  entry: ArchiveEntry,
): Promise<void> {
  const existing = await readArchive(memoryDir)
  // Replace if filename matches (idempotent)
  const filtered = existing.filter(e => e.filename !== entry.filename)
  filtered.push(entry)
  await writeArchive(memoryDir, filtered)
}

// ---------------------------------------------------------------------------
// Remove — delete a single entry by filename (incremental, used by restore())
// ---------------------------------------------------------------------------

/**
 * Remove a single entry from ARCHIVE.md by filename.
 *
 * Used by RepairService.restore() for incremental manifest sync. If this was
 * the last entry, ARCHIVE.md is deleted (writeArchive handles empty case).
 *
 * No-op if ARCHIVE.md doesn't exist or filename not in manifest.
 */
export async function removeEntry(
  memoryDir: string,
  filename: string,
): Promise<void> {
  const existing = await readArchive(memoryDir)
  const filtered = existing.filter(e => e.filename !== filename)
  // Only write if something changed (avoid touching mtime unnecessarily)
  if (filtered.length === existing.length) return
  await writeArchive(memoryDir, filtered)
}

// ---------------------------------------------------------------------------
// Query — check if a filename is in ARCHIVE.md
// ---------------------------------------------------------------------------

/**
 * Check if a filename has an entry in ARCHIVE.md.
 *
 * Used by store.ts / recall.ts to determine if a memory is archived without
 * reading the full file frontmatter. Faster than reading every file.
 */
export async function isArchived(
  memoryDir: string,
  filename: string,
): Promise<boolean> {
  const entries = await readArchive(memoryDir)
  return entries.some(e => e.filename === filename)
}

/**
 * Get a single entry from ARCHIVE.md by filename.
 *
 * Returns undefined if not found.
 */
export async function getEntry(
  memoryDir: string,
  filename: string,
): Promise<ArchiveEntry | undefined> {
  const entries = await readArchive(memoryDir)
  return entries.find(e => e.filename === filename)
}
