/**
 * archive-index.test.ts — v0.3.4 Phase 0 Archive Index Unit Tests
 *
 * Tests the ARCHIVE.md manifest layer:
 * - src/lifecycle/archive-types.ts: ArchiveEntry, buildArchiveLine, parseArchiveLine, header
 * - src/index/archive-index.ts: readArchive, writeArchive, addEntry, removeEntry, isArchived, getEntry
 *
 * Acceptance criteria covered: AC-1 through AC-4 + atomicity (AC-5) + lazy-create edge cases
 *
 * See: docs/superpowers/specs/v0.3.4/04-archive-index.md §9.1-9.2
 */

import { describe, test, expect, beforeEach, afterEach } from "vitest"
import { mkdtemp, mkdir, rm, writeFile, readFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { join } from "node:path"
import { tmpdir } from "node:os"

import {
  type ArchiveEntry,
  buildArchiveLine,
  parseArchiveLine,
  MANIFEST_AUTO_GENERATED_HEADER,
  isAutoGeneratedHeaderLine,
} from "../../src/lifecycle/archive-types.js"

import {
  getArchiveManifestPath,
  readArchive,
  writeArchive,
  addEntry,
  removeEntry,
  isArchived,
  getEntry,
} from "../../src/index/archive-index.js"

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

let tmpDir: string

beforeEach(async () => {
  tmpDir = await mkdtemp(join(tmpdir(), "archive-index-test-"))
})

afterEach(async () => {
  await rm(tmpDir, { recursive: true, force: true })
})

/** Create a simple memory file (for realistic test setups). */
async function createMemoryFile(filename: string, name?: string, body = "content"): Promise<void> {
  const frontmatter = [
    "---",
    `name: ${name ?? filename.replace(/\.md$/, "")}`,
    "type: user",
    "---",
    "",
    body,
  ].join("\n")
  await writeFile(join(tmpDir, filename), frontmatter, "utf-8")
}

/** Compute a quick string hash for idempotency checks. */
function hash(s: string): string {
  let h = 0
  for (let i = 0; i < s.length; i++) {
    h = ((h << 5) - h + s.charCodeAt(i)) | 0
  }
  return String(h)
}

// ---------------------------------------------------------------------------
// Section 1: buildArchiveLine — manifest line formatting
// ---------------------------------------------------------------------------

describe("buildArchiveLine", () => {
  test("includes description when present", () => {
    const entry: ArchiveEntry = {
      filename: "test.md",
      title: "Test Memory",
      description: "A test memory for unit testing",
      archivedAt: 1000,
    }
    expect(buildArchiveLine(entry)).toBe("- [Test Memory](test.md) — A test memory for unit testing")
  })

  test("omits em-dash when description is empty string", () => {
    const entry: ArchiveEntry = {
      filename: "test.md",
      title: "Test Memory",
      description: "",
      archivedAt: 1000,
    }
    expect(buildArchiveLine(entry)).toBe("- [Test Memory](test.md)")
  })

  test("omits em-dash when description is only whitespace", () => {
    const entry: ArchiveEntry = {
      filename: "test.md",
      title: "Test Memory",
      description: "   ",
      archivedAt: 1000,
    }
    expect(buildArchiveLine(entry)).toBe("- [Test Memory](test.md)")
  })

  test("handles special characters in title and filename", () => {
    const entry: ArchiveEntry = {
      filename: "session_2026-07-17-v0.3.2-section4.md",
      title: "Session: v0.3.2 Section 4 — Cache, Repeat",
      description: "Cache, repeat stats",
      archivedAt: 1000,
    }
    expect(buildArchiveLine(entry)).toBe(
      "- [Session: v0.3.2 Section 4 — Cache, Repeat](session_2026-07-17-v0.3.2-section4.md) — Cache, repeat stats",
    )
  })
})

// ---------------------------------------------------------------------------
// Section 2: parseArchiveLine — manifest line parsing
// ---------------------------------------------------------------------------

describe("parseArchiveLine", () => {
  test("parses line with description", () => {
    const result = parseArchiveLine("- [Test Memory](test.md) — A test memory")
    expect(result).toEqual({
      title: "Test Memory",
      filename: "test.md",
      description: "A test memory",
    })
  })

  test("parses line without description", () => {
    const result = parseArchiveLine("- [Test Memory](test.md)")
    expect(result).toEqual({
      title: "Test Memory",
      filename: "test.md",
      description: "",
    })
  })

  test("parses line with em-dash in title", () => {
    const result = parseArchiveLine("- [Session: v0.3.2 — Cache](session.md) — Cache description")
    expect(result).toEqual({
      title: "Session: v0.3.2 — Cache",
      filename: "session.md",
      description: "Cache description",
    })
  })

  test("returns null for line with plain hyphen separator (requires em-dash —)", () => {
    const result = parseArchiveLine("- [Test Memory](test.md) - A test memory")
    // The regex only accepts em-dash (U+2014) as separator, not plain hyphen (U+002D)
    expect(result).toBeNull()
  })

  test("returns null for non-matching line", () => {
    expect(parseArchiveLine("not a manifest line")).toBeNull()
    expect(parseArchiveLine("# Heading")).toBeNull()
    expect(parseArchiveLine("")).toBeNull()
  })

  test("returns null for AUTO-GENERATED header", () => {
    expect(parseArchiveLine(MANIFEST_AUTO_GENERATED_HEADER)).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// Section 3: isAutoGeneratedHeaderLine — header detection
// ---------------------------------------------------------------------------

describe("isAutoGeneratedHeaderLine", () => {
  test("returns true for AUTO-GENERATED header", () => {
    expect(isAutoGeneratedHeaderLine(MANIFEST_AUTO_GENERATED_HEADER)).toBe(true)
  })

  test("returns true for header with leading whitespace", () => {
    expect(isAutoGeneratedHeaderLine(`  ${MANIFEST_AUTO_GENERATED_HEADER}`)).toBe(true)
  })

  test("returns false for normal manifest line", () => {
    expect(isAutoGeneratedHeaderLine("- [Test](test.md)")).toBe(false)
  })

  test("returns false for empty string", () => {
    expect(isAutoGeneratedHeaderLine("")).toBe(false)
  })
})

// ---------------------------------------------------------------------------
// Section 4: readArchive + writeArchive — full manifest CRUD
// ---------------------------------------------------------------------------

describe("readArchive", () => {
  test("returns empty array when ARCHIVE.md does not exist (AC-1)", async () => {
    const entries = await readArchive(tmpDir)
    expect(entries).toEqual([])
  })

  test("reads entries from existing ARCHIVE.md", async () => {
    const content =
      "<!-- AUTO-GENERATED — DO NOT EDIT -->\r\n" +
      "\r\n" +
      "- [Old Session](session_old.md) — An old session\r\n" +
      "- [Stale Pref](stale.md) — A stale preference\r\n"
    await writeFile(join(tmpDir, "ARCHIVE.md"), content, "utf-8")

    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(2)
    expect(entries[0].filename).toBe("session_old.md")
    expect(entries[1].filename).toBe("stale.md")
  })

  test("skips blank lines and AUTO-GENERATED header", async () => {
    const content =
      "<!-- AUTO-GENERATED — DO NOT EDIT -->\r\n" +
      "\r\n" +
      "- [Only](only.md) — The only entry\r\n"
    await writeFile(join(tmpDir, "ARCHIVE.md"), content, "utf-8")

    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(1)
    expect(entries[0].filename).toBe("only.md")
  })

  test("handles CRLF line endings", async () => {
    const content =
      "<!-- AUTO-GENERATED — DO NOT EDIT -->\r\n" +
      "\r\n" +
      "- [CRLF Test](crlf_test.md) — CRLF content\r\n"
    await writeFile(join(tmpDir, "ARCHIVE.md"), content, "utf-8")

    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(1)
    expect(entries[0].filename).toBe("crlf_test.md")
  })
})

describe("writeArchive", () => {
  test("writes sorted entries with AUTO-GENERATED header", async () => {
    const entries: ArchiveEntry[] = [
      { filename: "z.md", title: "Z Entry", description: "Last", archivedAt: 1 },
      { filename: "a.md", title: "A Entry", description: "First", archivedAt: 2 },
    ]
    await writeArchive(tmpDir, entries)

    const content = await readFile(join(tmpDir, "ARCHIVE.md"), "utf-8")
    expect(content).toContain(MANIFEST_AUTO_GENERATED_HEADER)
    expect(content).toContain("- [A Entry](a.md) — First")
    expect(content).toContain("- [Z Entry](z.md) — Last")

    // A should come before Z (alphabetical sort)
    const aIdx = content.indexOf("A Entry")
    const zIdx = content.indexOf("Z Entry")
    expect(aIdx).toBeLessThan(zIdx)
  })

  test("lazy-deletes ARCHIVE.md when entries is empty", async () => {
    // Create an existing ARCHIVE.md first
    await writeFile(join(tmpDir, "ARCHIVE.md"), "- [Old](old.md)\n", "utf-8")
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(true)

    // Write empty entries
    await writeArchive(tmpDir, [])
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
  })

  test("no-ops deleting non-existent ARCHIVE.md when entries is empty", async () => {
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
    await writeArchive(tmpDir, [])
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
  })

  test("output is idempotent (AC-4 — same input = same hash)", async () => {
    const entries: ArchiveEntry[] = [
      { filename: "b.md", title: "B", description: "Second", archivedAt: 1 },
      { filename: "a.md", title: "A", description: "First", archivedAt: 2 },
    ]

    await writeArchive(tmpDir, entries)
    const content1 = await readFile(join(tmpDir, "ARCHIVE.md"), "utf-8")

    await writeArchive(tmpDir, entries)
    const content2 = await readFile(join(tmpDir, "ARCHIVE.md"), "utf-8")

    expect(hash(content1)).toBe(hash(content2))
  })
})

// ---------------------------------------------------------------------------
// Section 5: addEntry — incremental manifest append
// ---------------------------------------------------------------------------

describe("addEntry", () => {
  test("adds entry to non-existent ARCHIVE.md (lazy-create)", async () => {
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)

    await addEntry(tmpDir, {
      filename: "new.md",
      title: "New Entry",
      description: "Just added",
      archivedAt: Date.now(),
    })

    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(true)
    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(1)
    expect(entries[0].filename).toBe("new.md")
  })

  test("adds entry to existing ARCHIVE.md", async () => {
    await writeArchive(tmpDir, [
      { filename: "first.md", title: "First", description: "desc", archivedAt: 1 },
    ])

    await addEntry(tmpDir, {
      filename: "second.md",
      title: "Second",
      description: "Also added",
      archivedAt: 2,
    })

    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(2)
  })

  test("replaces existing entry with same filename (idempotent)", async () => {
    await addEntry(tmpDir, {
      filename: "dup.md",
      title: "Original Title",
      description: "original",
      archivedAt: 100,
    })

    await addEntry(tmpDir, {
      filename: "dup.md",
      title: "Updated Title",
      description: "updated",
      archivedAt: 200,
    })

    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(1)
    expect(entries[0].title).toBe("Updated Title")
    expect(entries[0].description).toBe("updated")
  })
})

// ---------------------------------------------------------------------------
// Section 6: removeEntry — incremental manifest removal
// ---------------------------------------------------------------------------

describe("removeEntry", () => {
  test("removes entry by filename", async () => {
    await addEntry(tmpDir, { filename: "keep.md", title: "Keep", description: "", archivedAt: 1 })
    await addEntry(tmpDir, { filename: "remove.md", title: "Remove", description: "", archivedAt: 2 })

    await removeEntry(tmpDir, "remove.md")

    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(1)
    expect(entries[0].filename).toBe("keep.md")
  })

  test("no-op when filename not in manifest", async () => {
    await addEntry(tmpDir, { filename: "only.md", title: "Only", description: "", archivedAt: 1 })
    await removeEntry(tmpDir, "nonexistent.md")

    const entries = await readArchive(tmpDir)
    expect(entries).toHaveLength(1)
  })

  test("no-op when ARCHIVE.md does not exist", async () => {
    await expect(removeEntry(tmpDir, "nothing.md")).resolves.toBeUndefined()
  })

  test("lazy-deletes ARCHIVE.md on last entry removal", async () => {
    await addEntry(tmpDir, { filename: "last.md", title: "Last", description: "", archivedAt: 1 })
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(true)

    await removeEntry(tmpDir, "last.md")
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
  })
})

// ---------------------------------------------------------------------------
// Section 7: isArchived + getEntry — query functions
// ---------------------------------------------------------------------------

describe("isArchived", () => {
  test("returns false when ARCHIVE.md does not exist", async () => {
    expect(await isArchived(tmpDir, "any.md")).toBe(false)
  })

  test("returns true for archived filename", async () => {
    await addEntry(tmpDir, { filename: "archived.md", title: "Arch", description: "", archivedAt: 1 })
    expect(await isArchived(tmpDir, "archived.md")).toBe(true)
  })

  test("returns false for non-archived filename", async () => {
    await addEntry(tmpDir, { filename: "archived.md", title: "Arch", description: "", archivedAt: 1 })
    expect(await isArchived(tmpDir, "active.md")).toBe(false)
  })
})

describe("getEntry", () => {
  test("returns undefined when ARCHIVE.md does not exist", async () => {
    expect(await getEntry(tmpDir, "any.md")).toBeUndefined()
  })

  test("returns entry when found", async () => {
    await addEntry(tmpDir, {
      filename: "found.md",
      title: "Found Entry",
      description: "I was found",
      archivedAt: 42,
    })
    const entry = await getEntry(tmpDir, "found.md")
    expect(entry).toBeDefined()
    expect(entry!.title).toBe("Found Entry")
  })

  test("returns undefined when filename not in manifest", async () => {
    await addEntry(tmpDir, { filename: "present.md", title: "Present", description: "", archivedAt: 1 })
    expect(await getEntry(tmpDir, "absent.md")).toBeUndefined()
  })
})

// ---------------------------------------------------------------------------
// Section 8: Acceptance Criteria — AC-1 through AC-5
// ---------------------------------------------------------------------------

describe("AC-1: fresh install has no ARCHIVE.md", () => {
  test("fresh directory has no ARCHIVE.md", async () => {
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
    expect(existsSync(join(tmpDir, "MEMORY.md"))).toBe(false)
  })

  test("creating active memory does not create ARCHIVE.md", async () => {
    await createMemoryFile("test.md", "Test")
    // Active file alone should not trigger ARCHIVE.md
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
  })
})

describe("AC-2: first archive creates ARCHIVE.md and moves entry", () => {
  test("archive moves entry from active to archive manifest", async () => {
    // Create an active memory + MEMORY.md with it
    await createMemoryFile("active_test.md", "Active Test")
    const memoryMdContent =
      MANIFEST_AUTO_GENERATED_HEADER + "\r\n\r\n" + "- [Active Test](active_test.md) — A test memory\r\n"
    await writeFile(join(tmpDir, "MEMORY.md"), memoryMdContent, "utf-8")

    // Simulate archive: add to ARCHIVE.md, remove from MEMORY.md
    await addEntry(tmpDir, {
      filename: "active_test.md",
      title: "Active Test",
      description: "A test memory",
      archivedAt: Date.now(),
    })

    // ARCHIVE.md should now exist with the entry
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(true)
    const archiveContent = await readFile(join(tmpDir, "ARCHIVE.md"), "utf-8")
    expect(archiveContent).toContain("active_test.md")
  })
})

describe("AC-3: restore moves entry back and deletes empty ARCHIVE.md", () => {
  test("restore removes entry from ARCHIVE.md and deletes empty file", async () => {
    // Add one entry to ARCHIVE.md
    await addEntry(tmpDir, {
      filename: "restored.md",
      title: "Restored",
      description: "Will be restored",
      archivedAt: Date.now(),
    })
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(true)

    // Simulate restore: remove from ARCHIVE.md
    await removeEntry(tmpDir, "restored.md")

    // ARCHIVE.md should be deleted (was the only entry)
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
  })
})

describe("AC-4: rebuild is idempotent", () => {
  test("writeArchive twice produces identical hash", async () => {
    const entries: ArchiveEntry[] = [
      { filename: "a.md", title: "A", description: "Entry A", archivedAt: 1 },
      { filename: "b.md", title: "B", description: "Entry B", archivedAt: 2 },
    ]

    await writeArchive(tmpDir, entries)
    const h1 = hash(await readFile(join(tmpDir, "ARCHIVE.md"), "utf-8"))

    await writeArchive(tmpDir, entries)
    const h2 = hash(await readFile(join(tmpDir, "ARCHIVE.md"), "utf-8"))

    expect(h1).toBe(h2)
  })

  test("readArchive + writeArchive round-trip is stable", async () => {
    const entries: ArchiveEntry[] = [
      { filename: "x.md", title: "X", description: "Desc X", archivedAt: 10 },
      { filename: "y.md", title: "Y", description: "Desc Y", archivedAt: 20 },
    ]
    await writeArchive(tmpDir, entries)

    // Read back and re-write
    const readBack = await readArchive(tmpDir)
    await writeArchive(tmpDir, readBack)

    const content = await readFile(join(tmpDir, "ARCHIVE.md"), "utf-8")
    expect(content).toContain("x.md")
    expect(content).toContain("y.md")
    expect(content).toContain(MANIFEST_AUTO_GENERATED_HEADER)
  })
})

// ---------------------------------------------------------------------------
// Section 9: Edge cases
// ---------------------------------------------------------------------------

describe("edge cases", () => {
  test("handles many entries without performance regression", async () => {
    const entries: ArchiveEntry[] = []
    for (let i = 0; i < 100; i++) {
      entries.push({
        filename: `mem_${i}.md`,
        title: `Memory ${i}`,
        description: `Description ${i}`,
        archivedAt: i,
      })
    }
    await writeArchive(tmpDir, entries)

    const readBack = await readArchive(tmpDir)
    expect(readBack).toHaveLength(100)
  })

  test("lazy-create: ARCHIVE.md not created until writeArchive with entries", async () => {
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
    // readArchive on non-existent should not create the file
    await readArchive(tmpDir)
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
  })

  test("lazy-delete: removing all entries deletes ARCHIVE.md", async () => {
    await addEntry(tmpDir, { filename: "temp.md", title: "Temp", description: "", archivedAt: 1 })
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(true)

    await removeEntry(tmpDir, "temp.md")
    expect(existsSync(join(tmpDir, "ARCHIVE.md"))).toBe(false)
  })

  test("getArchiveManifestPath returns correct path", async () => {
    const path = getArchiveManifestPath(tmpDir)
    expect(path).toBe(join(tmpDir, "ARCHIVE.md"))
  })
})
