/**
 * opencode-memory — Archive Index Types (v0.3.4 Phase 0)
 *
 * Type definitions for ARCHIVE.md manifest entries.
 *
 * Concern separation:
 * - `src/lifecycle/types.ts` answers "what lifecycle state is this memory in?"
 * - `src/lifecycle/archive-types.ts` answers "where in the index is this archived memory referenced?"
 *
 * ARCHIVE.md is a manifest (index) of archived memories — it stores only
 * metadata pointers (filename, title, description, archivedAt), NEVER full
 * memory file contents. Memory file bodies remain in their original `.md` files.
 *
 * See docs/superpowers/specs/v0.3.4/04-archive-index.md for full design.
 */

/**
 * A single entry in the ARCHIVE.md manifest.
 *
 * Maps to one line in ARCHIVE.md:
 *   `- [${title}](${filename}) — ${description}`
 *
 * Filename is relative to the memory dir (scope-specific). Same convention
 * as MEMORY.md entries — see src/store.ts buildIndexLine().
 */
export interface ArchiveEntry {
  /** Filename relative to memory dir, e.g. "session_2026-07-17-x.md" */
  filename: string
  /** Title from frontmatter.name (or filename basename if missing) */
  title: string
  /** One-line hook from frontmatter.description (may be empty string) */
  description: string
  /** Epoch ms — when the memory was archived (from frontmatter.archivedAt) */
  archivedAt: number
  /** Optional reason for archiving (from audit log, may be omitted in manifest) */
  reason?: string
}

/**
 * Build a single manifest line from an ArchiveEntry.
 *
 * Format matches MEMORY.md's buildIndexLine for visual consistency:
 *   `- [Title](filename.md) — description`
 *
 * If description is empty, the em-dash separator is omitted:
 *   `- [Title](filename.md)`
 */
export function buildArchiveLine(entry: ArchiveEntry): string {
  const desc = entry.description.trim()
  if (desc) {
    return `- [${entry.title}](${entry.filename}) — ${desc}`
  }
  return `- [${entry.title}](${entry.filename})`
}

/**
 * Parse a manifest line into partial ArchiveEntry fields.
 *
 * Returns null if the line is not a valid manifest entry.
 * Only extracts filename + title + description — archivedAt must be read
 * from the actual memory file's frontmatter (manifest doesn't store epoch ms).
 *
 * Format expected:
 *   `- [Title](filename.md) — description`
 *   `- [Title](filename.md)` (no description)
 */
export function parseArchiveLine(line: string): { filename: string; title: string; description: string } | null {
  // Match: - [Title](filename.md) — description
  // OR:    - [Title](filename.md)
  const m = line.match(/^-\s+\[([^\]]*)\]\(([^)]+)\)\s*(?:—\s*(.*))?$/)
  if (!m) return null
  return {
    title: m[1].trim(),
    filename: m[2].trim(),
    description: (m[3] ?? "").trim(),
  }
}

/**
 * The AUTO-GENERATED header line prepended to both MEMORY.md and ARCHIVE.md.
 *
 * This is a markdown HTML comment — not rendered, not a manifest entry.
 * It is preserved during all read/write/rebuild operations and excluded
 * from entry count.
 *
 * Rationale (Momus R4): users editing MEMORY.md manually will lose changes
 * on next rebuild. The header makes this visible.
 */
export const MANIFEST_AUTO_GENERATED_HEADER =
  "<!-- AUTO-GENERATED — DO NOT EDIT. See docs/superpowers/specs/v0.3.4/04-archive-index.md -->"

/**
 * Check if a line is the AUTO-GENERATED header (for skip during parsing).
 */
export function isAutoGeneratedHeaderLine(line: string): boolean {
  return line.trim().startsWith("<!-- AUTO-GENERATED")
}
